package com.openai.services;

import org.springframework.ai.client.AiClient;
import org.springframework.ai.prompt.PromptTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import lombok.extern.slf4j.Slf4j;

/**
 * @author madhankumar
 */
@Service
@Slf4j
public class AIServiceHelper {

	@Autowired
	AiClient aiClient;

	@Value("${spring.ai.openai.api-key}")
	private String apiKey;

	/**
	 * Generates a response to the provided question using the AI client.
	 *
	 * @param question The question asked by the user.
	 * @return The response generated by the AI client.
	 */
	public String chat(String question){
		/* Initialize Variable */
		PromptTemplate promptTemplate = null;
		try {
			/* Create a prompt template using the question */
			promptTemplate = new PromptTemplate(question);
		}catch(Exception e) {
			log.error("error : "+e.getMessage());

		}
		/* Generate a response using the AI client and return the text of the generated response */
		return this.aiClient.generate(promptTemplate.create()).getGeneration().getText();
	}

	/**
	 * Generates a document content for the specified topic using the AI client.
	 *
	 * @param topic The topic for which the document content needs to be generated.
	 * @return The generated document content as a string.
	 */
	public String generateDocument(String topic) {
		/* Initialize variable */
		PromptTemplate promptTemplate =null;
		try {

			/* Create a prompt template with place holders for the topic and document content instructions */
			promptTemplate = new PromptTemplate("""
					Generate document content for a {topic}. 
					It should be at least two pages long and include comprehensive information covering all aspects of the topic, 
					including background information, current trends or developments, relevant statistics or data, key concepts or 
					theories, potential challenges, and future outlook. The document should be well-structured with clear headings
					and sub-headings, and it should provide an in-depth analysis that offers insights and engages the reader effectively.
					      """);

			/* Replace the placeholder {topic} with the actual topic provided */
			promptTemplate.add("topic", topic);
		}catch(Exception e) {
			log.error("error : "+e.getMessage());
		}

		/* Generate document content using the AI client and return the text of the generated content */
		return this.aiClient.generate(promptTemplate.create()).getGeneration().getText();
	}

}
